{% set name = "httpx-oauth" %}
{% set version = "0.13.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 566d7147a2cf861fba4fa42ab065e766622e2f142bdc29ab6a9a6b630eb8d1ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-regex-commit
    - hatchling
    - pip
    - python >=3.8
  run:
    - httpx >=0.18,<0.27
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - httpx_oauth
    - httpx_oauth.clients
    - httpx_oauth.integrations
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - fastapi
    - pip
    # pytest-asyncio doesnt fully support pytest 8 yet
    - pytest <8.0.0
    - pytest-asyncio
    - pytest-mock
    - respx
    - requests
    - starlette

about:
  home: https://github.com/frankie567/httpx-oauth
  doc_url: https://frankie567.github.io/httpx-oauth/
  summary: Async OAuth client using HTTPX.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankie567
    - thewchan
