{% set name = "httpx-oauth" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ed7359053ac1b1652adbb18b074b6709bcee54e28fb76dd8062c408cfc4589c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-regex-commit
    - hatchling
    - pip
    - python >=3.7
  run:
    - httpx >=0.18,<0.24
    - python >=3.7
    - typing-extensions

test:
  source_files:
    - tests
  imports:
    - httpx_oauth
    - httpx_oauth.clients
    - httpx_oauth.integrations
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - fastapi
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    - respx
    - requests
    - starlette

about:
  home: https://github.com/frankie567/httpx-oauth
  doc_url: https://frankie567.github.io/httpx-oauth/
  summary: Async OAuth client using HTTPX.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankie567
    - thewchan
